### ISSUE TITLE
Multiple dex files define Lcom/google/ads/AdRequest$ErrorCode

### ISSUE THREAD

**Issue by Trexology** [floatinghotpot/cordova-plugin-admob#196]
Cordova cli : 5.0
ionic: 1.0
Android platform: 4.0.2
Android build API : 22

cordova-plugin-admobpro:  2.8.1

keep getting this error:

UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/google/ads/AdRequest$ErrorCode;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)

It works fine with the iOS version but not android. please help

**Comment by floatinghotpot** [comment]
The plugin cordova-plugin-admobpro is referencing to google play services jar in your default android SDK with tag framework. 

From the error, it seems that multiple google play services jar causing conflict, please double check whether other plugins contains the jar.

**Comment by Trexology** [comment]
@floatinghotpot Now that you mention it, i believe the "google analytic plugins" also uses google play services.

Am i suppose to remove the jar file from either one of the plugin? If so, how should i do that?

Thx for the fast reply anyway, cheers!

**Comment by floatinghotpot** [comment]
Using framework tag  is recommended by Google team. 

And, the google play services plugin is deprecated. See:
https://github.com/MobileChromeApps/google-play-services

Please report a bug to the google analytics plugin.

**Comment by marian2js** [comment]
I had the same problem after create a new project with ionic and add the plugin cordova-plugin-admobpro.

I fixed it by doing:

cordova plugin remove com.google.playservices    // version 19
cordova plugin add com.google.playservices         // version 21

I am not sure why the error occurred, but this solved it for me.

**Comment by samundra** [comment]
@marian2js Thanks for sharing the fix. I also added the admob following this tutorial and got to the error mentioned. After googling desperately landed to this gist :)

**Comment by faustoct** [comment]
thanks. works like a charm!
